DROP TABLE IF EXISTS travelist_articles;

CREATE TABLE travelist_articles (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  image_url TEXT NOT NULL,
  author_id INTEGER REFERENCES travelist_users(id),
  title TEXT NOT NULL,
  content TEXT,
  date_created TIMESTAMP DEFAULT now() NOT NULL,
  article_category TEXT REFERENCES travelist_categories(name)
);