CREATE TABLE travelist_users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  fullname TEXT NOT NULL,
  username TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  date_created TIMESTAMP DEFAULT now() NOT NULL,
  date_modified TIMESTAMP
);

ALTER TABLE travelist_articles
  ADD COLUMN 
    author_id INTEGER REFERENCES travelist_users(id)
    ON DELETE SET NULL;